# This is the same as docker run --name crm-db -e POSTGRES_USER=crm_user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=crm_dev -p 5432:5432 -d postgres:15
services:
  db:
    image: postgres:15
    container_name: crm-db
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: