services:
  - name: crm
    type: web
    runtime: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npx --yes serve -s dist -l $PORT
    region: ohio
    autoDeployTrigger: "off"
    envVars:
      - key: VITE_API_URL
        fromService:
          name: crm-server
          type: web
          property: hostport

  - name: crm-server
    type: web
    runtime: node
    plan: free
    buildCommand: cd server && npm install && npx prisma migrate reset && npm run build
    startCommand: cd server && npm start
    region: ohio
    autoDeployTrigger: "off"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: crm-database
          property: connectionString

databases:
  - name: crm-database
    plan: free
    region: ohio
    ipAllowList: []

