services:
  - name: crm
    type: web
    runtime: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: crm-server
          type: web
          property: host

  - name: crm-server
    type: web
    runtime: node
    plan: free
    # We are doing a reset here for demo purposes; in a production app, consider running migrations instead (e.g., `npx prisma migrate deploy`)
    buildCommand: cd server && npm install && npx prisma migrate reset --force && npm run build
    startCommand: cd server && npm start
    region: ohio
    autoDeployTrigger: off
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: crm-database
          property: connectionString

databases:
  - name: crm-database
    plan: free
    region: ohio
    ipAllowList: []

